-- Link conditions to encounters via the encounter diagnosis table
SELECT 
    e.UPID, 
    e.ID, 
    erc.SNOMED as ENCOUNTER_REASON_CODE_SNOMED,
    erc.ICD10CM AS ENCOUNTER_REASON_CODE_ICD10,
    c.CODE_SNOMED as ENCOUNTER_DIAGNOSIS_SNOMED,
    c.CODE_ICD10CM AS ENCOUNTER_DIAGNOSIS_ICD10,
    p.NAME_FAMILY,
    p.NAME_GIVEN_1
FROM ENCOUNTER e
LEFT JOIN ENCOUNTER_REASON_CODE erc
    ON e.ID = erc.ENCOUNTER_ID
LEFT JOIN ENCOUNTER_DIAGNOSIS ed
    ON e.ID =  ed.ENCOUNTER_ID
LEFT JOIN CONDITION c
    ON ed.CONDITION_ID = c.ID
LEFT JOIN ENCOUNTER_PARTICIPANT ep
    ON e.ID = ep.ENCOUNTER_ID
LEFT JOIN PRACTITIONER p
    ON p.ID = ep.INDIVIDUAL_PRACTITIONER_ID
