-- Link conditions to encounters via the encounter diagnosis table
SELECT 
    e.UPID AS ZUS_UPID, 
    e.ID AS ENCOUNTER_ID, 
    erc.SNOMED AS ENCOUNTER_REASON_CODE_SNOMED,
    erc.ICD10CM AS ENCOUNTER_REASON_CODE_ICD10,
    c.CODE_SNOMED AS ENCOUNTER_DIAGNOSIS_SNOMED,
    c.CODE_ICD10CM AS ENCOUNTER_DIAGNOSIS_ICD10,
    p.NAME_FAMILY AS PRACTITIONER_FAMILY_NAME,
    p.NAME_GIVEN_1 AS PRACTITIONER_GIVEN_NAME
FROM ENCOUNTER e
LEFT JOIN ENCOUNTER_REASON_CODE erc
    ON e.ID = erc.ENCOUNTER_ID
LEFT JOIN ENCOUNTER_DIAGNOSIS ed
    ON e.ID =  ed.ENCOUNTER_ID
LEFT JOIN CONDITION c
    ON ed.CONDITION_ID = c.ID
LEFT JOIN ENCOUNTER_PARTICIPANT ep
    ON e.ID = ep.ENCOUNTER_ID
LEFT JOIN PRACTITIONER p
    ON p.ID = ep.INDIVIDUAL_PRACTITIONER_ID
